FROM debian
RUN apt-get update
RUN apt-get install -y build-essential swig python3 python3-pip ipython3
RUN pip3 install numpy
RUN pip3 install cython
RUN pip3 install auto-sklearn
RUN pip3 install jupyter
RUN pip3 install prompt-toolkit==1.0.15
