version: '3'
services:
  autoscikitlearn:
    build:
      context: .
      dockerfile: Dockerfile.autoscikitlearn
    user: jovyan
    volumes:
      - ./:/app
    working_dir: /app
    command: "jupyter notebook --ip 0.0.0.0 --allow-root --NotebookApp.token=''"
    ports:
     - "8888:8888"

  tpot:
    build:
      context: .
      dockerfile: Dockerfile.tpot
    user: jovyan
    volumes:
      - ./:/app
    working_dir: /app
    command: "jupyter notebook --ip 0.0.0.0 --allow-root --NotebookApp.token=''"
    ports:
     - "8889:8888"
